# Base vars
distribution: focal
cuckoo_user: cuckoo
timezone: UTC

# Virtualization vars
virtualbox_ext_pack_ver: 6.1.6
virtualbox_version: 6.1

# Ports
cuckoo_web_port: 8080
cuckoo_api_port: 8081

# Virtual environment
cuckoo_dir: /opt/cuckoo
working_dir: /home/{{ cuckoo_user }}/.cuckoo
resources_dir: /home/{{ cuckoo_user }}/resources

# Configurations
mongodb_ip: 10.0.0.71
mongodb_port: 27017
build_dir: /usr/local/src/build
volatility_version: 2.5
yara_version: "4.0.2"

# Guest vars
# For usage with a prepped appliancecuckoo_vm_label: ie9win7-1
cuckoo_appliance: ie9win7-1.ova
# For usage with vmcloak
iso: Win7_HomePrem_SP1_German_COEM_x32.iso
iso_serial: XXXX-XXXX-XXXX-XXXX-XXXX

# Network vars
nic: eno1 #enx001e101f0000  # this will be the "dirty line"
cuckoo_guest_net_range: 192.168.56.0/24
cuckoo_guest_net: 192.168.56.  # For simpler string building
cuckoo_result_ip: 1
cuckoo_guest_ip: 101
guestnet_broadcast: 255
# Net ranges to protect from the VM traffic
protected_net_1: 10.0.0.0/24
protected_net_2: 192.168.178.0/24
