---
- name: Install python packages into virtualenv - {{ cuckoo_dir }}
  pip:
    virtualenv: "{{ cuckoo_dir }}"
    virtualenv_python: python2.7
    name: 
      - pip
      - setuptools
      - psycopg2
      - pydeep
      - openpyxl
      - ujson
      - pycrypto
      - distorm3==3.4.4
      - pytz
      - jsonschema 
      - cuckoo
  become: yes 

- name: Change owner of {{ cuckoo_dir }} directory
  become: yes
  file:
    path: "{{ cuckoo_dir }}"
    state: directory
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    recurse: true

- name: Setup Cuckoo Working Directory - {{ working_dir }}
  become: yes  
  become_user: "{{ cuckoo_user }}"
  command: "{{ cuckoo_dir }}/bin/cuckoo --cwd {{ working_dir }}"
  failed_when: result.rc != 1 and result.rc != 0
  register: result

- name: Change owner of {{ working_dir }} directory
  become: yes
  file:
    path: "{{ working_dir }}"
    state: directory
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    recurse: true

- name: Backup auxiliary.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/auxiliary.conf {{ working_dir }}/conf/auxiliary.conf.original"

- name: Backup avd.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/avd.conf {{ working_dir }}/conf/avd.conf.original"

- name: Backup cuckoo.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/cuckoo.conf {{ working_dir }}/conf/cuckoo.conf.original"

- name: Backup esx.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/esx.conf {{ working_dir }}/conf/esx.conf.original"

- name: Backup kvm.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/kvm.conf {{ working_dir }}/conf/kvm.conf.original"

- name: Backup memory.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/memory.conf {{ working_dir }}/conf/memory.conf.original"

- name: Backup physical.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/physical.conf {{ working_dir }}/conf/physical.conf.original"

- name: Backup processing.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/processing.conf {{ working_dir }}/conf/processing.conf.original"

- name: Backup qemu.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/qemu.conf {{ working_dir }}/conf/qemu.conf.original"

- name: Backup reporting.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/reporting.conf {{ working_dir }}/conf/reporting.conf.original"

- name: Backup routing.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/routing.conf {{ working_dir }}/conf/routing.conf.original"

- name: Backup virtualbox.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/virtualbox.conf {{ working_dir }}/conf/virtualbox.conf.original"

- name: Backup vmware.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/vmware.conf {{ working_dir }}/conf/vmware.conf.original"

- name: Backup vsphere.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/vsphere.conf {{ working_dir }}/conf/vsphere.conf.original"

- name: Backup xenserver.conf file
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "mv {{ working_dir }}/conf/xenserver.conf {{ working_dir }}/conf/xenserver.conf.original"

- name: Copy local Cuckoo configuration files to {{ working_dir }}/conf
  become: yes
  become_user: "{{ cuckoo_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ working_dir }}/conf"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644
  with_fileglob:
    - ../files/cuckoo_conf/*

- name: Copy local Cuckoo routing.conf-template file to {{ working_dir }}/conf
  become: yes
  become_user: "{{ cuckoo_user }}"
  template:
    src: routing.conf
    dest: "{{ working_dir }}/conf"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644

- name: Copy local Cuckoo reporting.conf-template file to {{ working_dir }}conf
  become: yes
  become_user: "{{ cuckoo_user }}"
  template:
    src: reporting.conf
    dest: "{{ working_dir }}/conf"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644

- name: Copy local Cuckoo virtualbox.conf-template file to {{ working_dir }}/conf
  become: yes
  become_user: "{{ cuckoo_user }}"
  template:
    src: virtualbox.conf
    dest: "{{ working_dir }}/conf"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644

- name: Install Cuckoo signature modules
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "{{ cuckoo_dir }}/bin/cuckoo community"
  failed_when: result.rc != 1 and result.rc != 0
  register: result

- name: Disable AppArmor profile for Tcpdump in Ubuntu
  become: yes
  shell: aa-disable /usr/sbin/tcpdump
  ignore_errors: true

- name: Set specific Linux capabilities to the Tcpdump binary
  become: yes
  shell: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
