---
- name: Install python packages into virtualenv - {{ cuckoo_dir }}
  pip:
    virtualenv: "{{ cuckoo_dir }}"
    virtualenv_python: python2.7
    name:
      - pip #==9.0.3
      - setuptools==44.0.0
      - psycopg2
      - pydeep
      - openpyxl
      - ujson
      - pycrypto
      #- distorm3==3.4.4
      - pytz
      - jsonschema
      - chardet==2.3.0
      - requests==2.13.0
      - sflock >=0.3.5
  become: yes

- name: Change owner of {{ build_dir }} directory
  become: yes
  file:
    path: "{{ build_dir }}"
    state: directory
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    recurse: true

# https://github.com/JPCERTCC/MalConfScan-with-Cuckoo
- name: Clone MalConfScan-with-Cuckoo repo
  git:
    repo: https://github.com/jpcertcc/malconfscan-with-cuckoo.git
    dest: "{{ build_dir }}/MalConfScan-with-Cuckoo/"
  become: yes # needed for write permissions on build dir
  become_user: "{{ cuckoo_user }}"
  when: is_malconfscan

- name: Remove potential patched cuckoo repo
  ansible.builtin.file:
    path: "{{ build_dir }}/Cuckoo-{{ cuckoo_version }}/"
    state: absent
  become: yes

- name: Clone Cuckoo's repo
  git:
    repo: https://github.com/cuckoosandbox/cuckoo.git
    dest: "{{ build_dir }}/Cuckoo-{{ cuckoo_version }}/"
    version: "{{ cuckoo_version }}"
    force: yes
  become: yes # needed for write permissions on build dir
  become_user: "{{ cuckoo_user }}"

- name: Apply patch to multiple files under basedir
  ansible.posix.patch:
    src: "{{ build_dir }}/MalConfScan-with-Cuckoo/malconfscan.patch"
    remote_src: yes
    basedir: "{{ build_dir }}/Cuckoo-{{ cuckoo_version }}/"
    strip: 1
  become_user: "{{ cuckoo_user }}" # neccessary for creating tmp dir
  become: yes
  when: is_malconfscan

# https://docs.cuckoosandbox.org/en/latest/development/package/
- name: Run monitor script to obtain the matching monitoring binaries
  become: yes
  become_user: "{{ cuckoo_user }}"
  shell: "{{ cuckoo_dir }}/bin/python2.7 stuff/monitor.py"
  args:
    chdir: "{{ build_dir }}/Cuckoo-{{ cuckoo_version }}/"

- name: Change owner of {{ cuckoo_dir }} directory
  become: yes
  file:
    path: "{{ cuckoo_dir }}"
    state: directory
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    recurse: true

# https://docs.cuckoosandbox.org/en/latest/development/package/
- name: Create tar ball from cuckoo to install in virtualenv
  become: yes
  become_user: "{{ cuckoo_user }}"
  shell: "{{ cuckoo_dir }}/bin/python2.7 setup.py sdist"
  args:
    chdir: "{{ build_dir }}/Cuckoo-{{ cuckoo_version }}/"

- name: Install cuckoo from local tarball in virtualenv
  become: yes
  become_user: "{{ cuckoo_user }}"
  pip:
    virtualenv: "{{ cuckoo_dir }}"
    virtualenv_python: python2.7
    name: "file:///{{ build_dir }}/Cuckoo-{{ cuckoo_version }}/dist/Cuckoo-{{ cuckoo_version }}.tar.gz"


- name: Fix known dependency problem with flask and werkzeug by downgrading werkzeug to 0.16.1
  # https://github.com/cuckoosandbox/cuckoo/issues/2958
  # https://stackoverflow.com/questions/60131900/weird-is-xhr-error-when-deploying-flask-app-to-heroku
  pip:
    virtualenv: "{{ cuckoo_dir }}"
    virtualenv_python: python2.7
    name:
      - werkzeug==0.16.1
  become: yes

