---
- name: Download and uncompress Volatility source
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  unarchive:
    src: https://github.com/volatilityfoundation/volatility/archive/{{ volatility_version }}.tar.gz
    dest: "{{ build_dir }}"
    remote_src: true

- name: Build Volatility
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: python setup.py build
  args:
    chdir: "{{ build_dir }}/volatility-{{ volatility_version }}"

- name: Install Volatility
  become: true
  become_method: sudo
  shell: python setup.py install
  args:
    chdir: "{{ build_dir }}/volatility-{{ volatility_version }}" 
    creates: /bin/vol.py
